# Generated by Django 4.0.4 on 2022-04-13 05:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelling_companion', '0002_trip_city_creator_userrelationships_triptravelers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrelationships',
            unique_together={('user1', 'user2')},
        ),
    ]
