# Generated by Django 4.0.4 on 2022-04-13 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelling_companion', '0005_remove_traveler_passport_number_passport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='passport',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='pointofdestination',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='triptravelers',
            old_name='creator',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='person',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
