# Generated by Django 4.0.4 on 2022-04-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelling_companion', '0009_alter_userrelationships_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pointofdestination',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelling_companion.trip'),
        ),
        migrations.AlterField(
            model_name='userrelationships',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
