# Generated by Django 4.0.4 on 2022-04-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling_companion', '0011_costitem_flight_location_tripaccommodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_location',
            field=models.ManyToManyField(blank=True, null=True, to='travelling_companion.location'),
        ),
    ]
