# Generated by Django 4.0.4 on 2022-04-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelling_companion', '0012_alter_trip_trip_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelling_companion.costitem'),
        ),
        migrations.AlterField(
            model_name='tripaccommodation',
            name='cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelling_companion.costitem'),
        ),
    ]
