# Generated by Django 4.0.4 on 2022-04-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling_companion', '0013_alter_flight_cost_alter_tripaccommodation_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='confirmation_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_location',
            field=models.ManyToManyField(blank=True, to='travelling_companion.location'),
        ),
    ]
